{"filename": "haskell-enclosed-exceptions-1.0.3-231-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-231", "desc": "Catching all exceptions from within an enclosed computation", "csize": "17680", "isize": "62402", "md5sum": "57a546dbfd28ad99454f3f2f9cb55579", "sha256sum": "271ef269de1778fac2d0239643087b9db82e4b962b39a360580e81d9bbc21b47", "pgpsig": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmQtAnoACgkQeGxj8zDXy5IxpA/9F6DtGzqDvZ/GpZhPVIRpBR5itzAoBmUucnNTYtXdIw6spHT43kPqhdDZjVdBnckPMCVdcwHC63+WEn2PSvkRK4vfL2FnQ8Ar81EOHtSwJom05OTB0c8d1jO2VAEq8HfEC0268oel2ltBwouWCdrYtj28WNvAtziXRP8ucY9PRFEdOtletoNO5kUo8vAV5HK9hSqf4/Kclr9SRaII7pxQJHjPjfh61r9N/GO5cPZyj5upoWwG3m+LTmkf6ypgtHeFA71RFJ5lwIDAo0lnxhBQnyI0DMhZ2y4vm5m/erPVPat1Fl+84/3T+Y1FMd8uK7MTPvWLsrL5WtQDjlUIAfkaQPxuIKADUE3xpgWMDRtOgR2wrm5zoh3Roe/pG0TDFOktEpxj+piuQtjMNRBlF69naV1LE/1+7CYRBg8hWKkgEtEP9fkreApQw3Zt4Jg9g7JA7s3qleA9hXf5oqxYUxWeSLVKFzcEcWhSMgeGmDQBJYYuZIc1RZMLZoUiKFEkITqaP+mN4yfNgRdGteTazG5CAOFg7mmWYdVlfm777/g17UvigQEperF3S9JvJzGkYAyFGiHXTP7GbzSxuzpFnY4PQ66Q+7Jp0Owtq2gIitmIpMGvJcwpfTNYPqcMzd24YNPjQ6dBo/AdU/D6Si375mxZuzW9URbBD6S3XxWX5nGe0GQ=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1680671328", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"], "tokens": ["haskell-enclosed-exceptions", "haskell-enclosed-exceptions_x86_64", "haskell-enclosed-exceptions_testing", "haskell-enclosed-exceptions_x86_64_testing"]}