{"filename": "python-zope-exceptions-6.0-1-any.pkg.tar.zst", "name": "python-zope-exceptions", "base": "python-zope-exceptions", "version": "6.0-1", "desc": "Generic exceptions and implementations for Zope", "csize": "39227", "isize": "230339", "sha256sum": "c6bcce5699273366fd91de5ce0548ba408fa2b69a36563e3a622169ebee8f235", "pgpsig": "iHUEABYKAB0WIQTrPXZP9dh+CBij4OXwXowSExrrXgUCaNlXpQAKCRDwXowSExrrXvMUAPwN9k0a2x9MAhniKEoL9avMPwuW7jtjC5ovKFM5eXiGXAEA+cPRMZPqz2AWNTbno1OLtZeTVsjinbM6rw4eG1xL4QQ=", "url": "https://github.com/zopefoundation/zope.exceptions", "license": "ZPL-2.1", "arch": "any", "builddate": "1759074185", "packager": "Carl Smedstad <carsme@archlinux.org>", "depends": ["python", "python-zope-interface"], "makedepends": ["git", "python-build", "python-installer", "python-setuptools", "python-wheel"], "checkdepends": ["python-zope-testrunner"]}