{"filename": "python-pytest-rerunfailures-13.0-1-any.pkg.tar.xz", "name": "python-pytest-rerunfailures", "base": "python-pytest-rerunfailures", "version": "13.0-1", "desc": "A plugin for py.test that re-runs failed tests to eliminate intermittent failures", "csize": "24056", "isize": "111581", "md5sum": "d649356d3b40f8c3ee0af43656ca773c", "sha256sum": "719ce745b397c87e818240ee3eb622162004be6a7f4083f480f7ccbff31055c5", "pgpsig": "iQIzBAABCAAdFiEEaLNTfzmjE7PldNBndxk/FSvb5qYFAmVfexgACgkQdxk/FSvb5qY4Hg//cbZPMoTZJ7LBqvBT0Y+A7k/IaglnPC3SdTtcB1BLdaF8woHN8TueI274+BdlcYnJpc3fSvU6ApCakJmi/BuT1wfnHGNBMdxLNW/C1OU8LRpb6lNUOgncxzBU+xh2hRq2ufcLNZtmSxK+YEKyqs6uDGDhbtbi5pjHUiJK8eQprg1zRgFZCeEEGDuKPirskn8agqmw3WB83rQxBYgpaoT2x0EJNNj09trnDvsW5M/j0WEZowpMoND+AFRHdpdAMP+hM5yErC/1rReH0ARA+Lsrg0sQ/v6MOrE6YDezpggYVDWA0EIv32HotE1aKvniOWmL/85r0d+Qz0ryjqPNJxAkEAD73vZisXhWsvfReROvdya9qFdps2vHnoD+Cycv55pCIteyEM9uJ/r5hUt14v+vl/WmtP1Y4YLj6+YnfHqCN1vRSziOPBpbt3Y/2kmHZg8A6GHaLgHQj0DvfiKShXzimLJwip2c/KOg66hRVP0AEZF3XKQP/zLP83hLkMDHgQJRqyn7PM6FeYcA8+NtWZDIbCZTSgaqgg7QOjcPuQxIEDKtJcvFKJ/ZsNtufZhzbV8dGxaUb2GXPcadJ+ontuoC0jTzThRcHYz1j0oLoMIyJaMiUhXT7kyiIyRzGpfcC32ocuNmIn3QX2g8Flw45SkWrXOTZUwXq2riFqfnzFBlIyc=", "url": "https://github.com/pytest-dev/pytest-rerunfailures/", "license": "MPL-2.0", "arch": "any", "builddate": "1700756235", "packager": "Arch Linux ARM Build System <builder+n1@archlinuxarm.org>", "depends": ["python", "python-importlib-metadata", "python-packaging", "python-pytest"], "optdepends": "python-pytest-xdist: for recovering from crashes", "makedepends": ["python-build", "python-installer", "python-setuptools", "python-wheel"], "checkdepends": ["python-pytest-xdist"], "tokens": ["python-pytest-rerunfailures", "python-pytest-rerunfailures_aarch64", "python-pytest-rerunfailures_testing", "python-pytest-rerunfailures_aarch64_testing"]}