{"filename": "haskell-enclosed-exceptions-1.0.3-242-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-242", "desc": "Catching all exceptions from within an enclosed computation", "csize": "17717", "isize": "62395", "md5sum": "b517080c0e8138fd6efe6b9b0c76f08a", "sha256sum": "7574ba917d2ab951a3e6b5d88140ac6d982e9d7cb5c876665bb8a900696cfc57", "pgpsig": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmVV+ZEACgkQeGxj8zDXy5Ln3A//RvX2UflIwKIgE3bTPACA+muKsfCiWjBy23w1C9j0dT8yL7NT+chk+BQwtqxnbcJQfj5cgCDbvFnkZNoq6/s4bTkcD0qRFrAQsbGPX+P1WGmAk7N6YmvSvq1VLZaTevrQeNLfMVatfeFE8ASblVPxT1bkmOlKw2CQUfvVjwjy07kzFZvQDK4mLmAIUQ4xmjgUmOIKm7faUrMmAbWr/RBuDVbnDUtSoe0CfYU03qSNptBVnyVHl+hF5kWVVxUcMelDRJVQZdeI8jM95hiUQ6miinyx8ccc623xAZlft5ODbp37xwwR/06g2cDQBaM3oP2TxcQ4Pnbk+BqUdnEOYkt2hNE90/S2lutTt4JVOb4GvIiACDjRE992OZH+ylZ8tuWgxBFTVHXKudyDBhVXklVYMO4u7i5d6xMgnxRPA+LaLVJDv81ytOF+dBgGBu7gFBEsDV43+fxh7fPykFdzgx6swVrPeKHLlVOsSCv0hLSDA6bC2dy1pBWDuxpvAh5Js7k2jheRW6Frto2ws8C4d0j/H8rWB80Q+O/UpVH7UDPFppC7PFq0ISWEYoUpKdDzB8b9Z7aJt1jbohd7NpVjoa59aFfWdQjwNN29Nb+/IWB4BZJYZ/aCuMkm8ODxe0rZx5ICHf1kpgu3hEFZdRivPAngTlg5+YcCRnreqpfXx0wnknI=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1700133246", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"], "tokens": ["haskell-enclosed-exceptions", "haskell-enclosed-exceptions_x86_64", "haskell-enclosed-exceptions_testing", "haskell-enclosed-exceptions_x86_64_testing"]}