{"filename": "lld-16.0.6-1-x86_64.pkg.tar.zst", "name": "lld", "base": "lld", "version": "16.0.6-1", "desc": "Linker from the LLVM project", "csize": "1890322", "isize": "6859262", "md5sum": "e9cc7c4f297ad0a477a3cf9e787a50b1", "sha256sum": "9f253579e9b8db502e74d4ab2efd1d3b16fa87143aec4554a8fefc3343fb3866", "pgpsig": "iQEzBAABCAAdFiEEhs/8qRjPOvRxR1iAUeixSKmZnDQFAmTfo/EACgkQUeixSKmZnDQnkAf8DrOezsLUzQ9uLWwKAbd8J5rH7hmgQ0jiccva7w4kZvjNnRVlm/H+X5kuz29kSzopxLh3Nc8hGpmdROGiYQ5NLYlLVvcpGP1nt7vdhjwsYNs+Gp3l2sf2cjA2FO+I66ywgDuOMjbZgOIrlI9gsfVvEEy9VaVHx9MxDORadkLCKSY7FbwEy3UNf1dJbvaxOQaMimY3I5cLfrcSZ3cmtskjCU6M02eaYj/GX+CmBA/Vb8ebNPb0IdfEYw25NgSLTxuL7LOj3nYMAE1bt4pDG455Ohhu/lqyGZkgzhFi1Vs7ZP2GgNYdUYF8z6fp5PT7AojxW2DIxrlMp1NmOLMOhJxCGQ==", "url": "https://lld.llvm.org/", "license": "custom:Apache 2.0 with LLVM Exception", "arch": "x86_64", "builddate": "1692377925", "packager": "Evangelos Foutras <foutrelis@archlinux.org>", "depends": ["llvm-libs", "gcc-libs", "zlib", "zstd"], "makedepends": ["llvm", "cmake", "ninja", "python-sphinx"], "tokens": ["lld", "lld_x86_64", "lld_testing", "lld_x86_64_testing"]}