{"filename": "lldb-19.1.6-1-x86_64.pkg.tar.zst", "name": "lldb", "base": "lldb", "version": "19.1.6-1", "desc": "Next generation, high-performance debugger", "csize": "6629772", "isize": "27073287", "md5sum": "d3d087a1ec025286b6b0ff67b7573b2d", "sha256sum": "1359a101b5940e38c965c3b6647d9bf299e69fa035d74354112afaa5f0f92d0b", "pgpsig": "iQEzBAABCAAdFiEEhs/8qRjPOvRxR1iAUeixSKmZnDQFAmd6dHwACgkQUeixSKmZnDSL7gf/S8XwdSHHzwgKjBF1fGrbf9KotAjZJjB54I0zpwQDZ7b6+S8Z3H2I3sR7LJwej0tiqUnWqLi33KsshfWR6W8ULZX8+44fSJa44aHA/T/V+Tth5lyPrpVocu2cx4zfARuTpp/9rrlt1OjtALhLQsTIfpgU9ZfAfZTd9q9whQVLG1SVYOVHvqfWnbsqQrCBN595pTMVJXHIu2LbLdyP/yoUtwQQRdAUivZkgxOPz+6JqP8kMP0ysQspZYMpxyQu3+b/D0NKuT2p5crxAS8WMB+9jaFHiWK9Jr69bsZ3A9MzLMmXiES7LktX5mWAwSMohRoTuKLuoHqwXvV1eEKTI/53LA==", "url": "https://lldb.llvm.org/", "license": "Apache-2.0 WITH LLVM-exception", "arch": "x86_64", "builddate": "1736078215", "packager": "Evangelos Foutras <foutrelis@archlinux.org>", "depends": ["llvm-libs", "clang", "gcc-libs", "zlib", "xz", "libedit", "ncurses", "libxml2", "python"], "makedepends": ["llvm", "cmake", "ninja", "swig", "python-sphinx"]}