{"filename": "python-exceptiongroup-1.1.3-2-any.pkg.tar.xz", "name": "python-exceptiongroup", "base": "python-exceptiongroup", "version": "1.1.3-2", "desc": "Backport of PEP 654 (exception groups)", "csize": "31388", "isize": "139366", "md5sum": "c10e60d5136adb9ac1974b96bf0c79ea", "sha256sum": "8b02ce2e264cf2d8214b617b31796fb54370c4e3f7ae44f228cc7b72f12e40d2", "pgpsig": "iQIzBAABCAAdFiEEaLNTfzmjE7PldNBndxk/FSvb5qYFAmTtRb4ACgkQdxk/FSvb5qbIVRAAwMNLzwrbZh2ls1AjWDkvHU0anojGvGVG5tv0Nk6xjrYGQyw9M7oYvkAsP+Dp2y+0ndbgsVzibL5xprYoVWelpF+uOd55QtAMsCDaIWODvvKQy8+Ai1yvDMcw6svhW2G00RXpVCe0FXwpgcJIObSc9N7EcK+jbihWnXBdawtylaF0CkXjT8nBQGakeYmd1rwdOhRuJS2cLHvV4jppGxEFbwmmD/Qg+42Ds8HSC8mv5Z9WyGhV9johlOVoogNmTs8/YQxKgFx2IxP5vnN5S8mwf/IZKU513NqMpTXiZGcFBO+eXTw3eWTNKnP3I7e+saK8MFNQfk1LEv8KU4QtVM5gJBgunFIU5GV3JoSBGFw8lMLVJpxYwZO1jDTxugoQZD/x3LmRC8JckGaIf6JH5Khso9JcaA1CarIxvNeOJ0FbNP6dd3oPlWNzLkOGfK11bMCUirs4350CdaMX6OUimnrUAThbrOsXtjjopznOqQ7h3fLs9MowhksOZtatMO9Rfg2zp2Hi7vQT6DOUHpvnaxIXICbB999GiBfezE4k86eq9sLZXcFL9tD4J/5X1wfXcpDTqRe38I3ZAmecI1ET1V0/Xt5N8VVXUIJK15/1sY+NxxPv0J+sixk+dbSZhJUqWi3tkCAPldawcoJSec4l116nbX4CiQqnxvu1H8XOmJ/coWs=", "url": "https://github.com/agronholm/exceptiongroup", "license": "MIT", "arch": "any", "builddate": "1693271473", "packager": "Arch Linux ARM Build System <builder+n1@archlinuxarm.org>", "depends": ["python"], "makedepends": ["python-build", "python-installer", "python-wheel", "python-flit-scm"], "checkdepends": ["python-pytest"], "tokens": ["python-exceptiongroup", "python-exceptiongroup_aarch64", "python-exceptiongroup_unstable", "python-exceptiongroup_aarch64_unstable"]}