{"filename": "python-exceptiongroup-1.2.1-2-any.pkg.tar.xz", "name": "python-exceptiongroup", "base": "python-exceptiongroup", "version": "1.2.1-2", "desc": "Backport of PEP 654 (exception groups)", "csize": "33428", "isize": "142862", "md5sum": "c8eeb6fcc5b4f349bda9b742a486fd6a", "sha256sum": "b827f21770d2dfa947f798e943ad339f3335639b42c48b28d294bbeb573ad200", "pgpsig": "iQIzBAABCAAdFiEEaLNTfzmjE7PldNBndxk/FSvb5qYFAmYuQ/EACgkQdxk/FSvb5qbDBA//YsNNPpd3Cdg1gfr3DsyhShs08BIdoO1pIV1vb3hs0oAxzxkRMBNV+kTd+kJ+/IP7DqN6+DHoY1kJBIpLQ4rdluk5b3Tz3m+0fwIE4u0cVYfd3oxv+CuuFLGCV19bKTfJpNCUmzegKpdXZY7AXmvzQ5aXMFIiskICg+gLAxidBmTdB5oQwuR1qfqejtXFtXAqqF6uSHkwdON5JChHIeUmPzt3TIXlJ4wMSGqtrKElU6/dgsRUh6xeEvi+PovJhBcUEtFVbHaxs1u94RvijGqYUtxvAczhJ5XnV+TwB8ktxtMV5whDXn/OngwDQzRGxdTzGQj0CXfZOK1HiuhM4XmglGU+xpjc7ly1B/VYMuqNW53aN5gpQonAWCdkLqCdGklS1uoVxSuEqy/AQ1Somrh35eL4jfqfw23SiRu3iK82YpCJDQk6f+UqhWCRru8W7N6LOk0Z0+aiY/vPp7whatCXuJe9xeI7tvTL73zHqqiohs8bN57f+X8E84X4hXvWyi4cJK0KqviyK0E7CsYMdG8QIWKL4eL23njBXljjIYsQ3+wdn8nSLjRH9+E3xJ1hsBdY+Q/oF6IwhR47ZYaBTIBtvFEpapkSi1NLiCus26U+tNtdsy/BY4wIm/sVqPRxj48KudX1J1r3X8LXWKIsUY53QrR511MOPbbg+Cc1X2eNCkY=", "url": "https://github.com/agronholm/exceptiongroup", "license": "MIT", "arch": "any", "builddate": "1714308070", "packager": "Arch Linux ARM Build System <builder+seattle@archlinuxarm.org>", "depends": ["python"], "makedepends": ["python-build", "python-installer", "python-wheel", "python-flit-scm"], "checkdepends": ["python-pytest"]}