{"filename": "python-zope-exceptions-6.0-1-any.pkg.tar.xz", "name": "python-zope-exceptions", "base": "python-zope-exceptions", "version": "6.0-1", "desc": "Generic exceptions and implementations for Zope", "csize": "36808", "isize": "230339", "md5sum": "6fe928a7cc95484b4f687c0b393af263", "sha256sum": "7a9702a0c4ba62bc988d0dc169e3ee488605b4d0e2a27400e68bfd269a358bec", "pgpsig": "iQIzBAABCAAdFiEEaLNTfzmjE7PldNBndxk/FSvb5qYFAmjgnGcACgkQdxk/FSvb5qbTMBAAhhn52Vpxp/+pn1z9R4MPTs9vhDbNRqSJ2juZEN8mz2YFLaSsxhoWxpHfEHEgp67TLI/6W0wGsI4etT20UDfqWgjHom0GwqkjC4HCC7psC8CTZCnomrHA10Dkub22+wt1H7rNgduOeykkZOAYH0betBbbKNwEKRQABpRoLJ8cPNuqqvXuWL6jiV7eSNaChFw/JqVajBJNwdVwFvpaE6QOggBE7wahRyEZdN6uGLhbS1hYbSUcfKexfYGr7jIcS6FWbfwC+122qsGKUnCWKb4D0mfnwY5xGye6b57ttN/oGtVUv7RSfeGpnnlnHW8kPnSGceaTO+sRvA29//GtIyAJdIjTZoFu69b/9YJvXyvFCZuCjhTaO1WFSLTVsz50sInvRwP9kwbPJR2KSrsNnu2lCn//9Tdp4jhC8tr7TJrbA3tBom4xVSYpr+KWzOJwxxVwz+ooOxS0Q39gt/GMmqc0caILCs8OloYixaXgIyd7hk2JxIApL2od29YLXK+rKZCJiWs7555LR3Vsxq4/CQh4XzOlKZKLmnL0ANUIhJNPc+SJGiesYYmZnAymwGePPrT/dtmpz3xby8CRU0oVCAA+vJE+3RgoHfUzUBH64/N/+PeJIM/xkrnQYmOBFXTHqugyaaXi87oz4YyWwGBq/wYh/6AcLFAaXSZqvTvzN8DqNIQ=", "url": "https://github.com/zopefoundation/zope.exceptions", "license": "ZPL-2.1", "arch": "any", "builddate": "1759550549", "packager": "Arch Linux ARM Build System <builder+n1@archlinuxarm.org>"}