{"filename": "python-pytest-rerunfailures-15.1-1-any.pkg.tar.xz", "name": "python-pytest-rerunfailures", "base": "python-pytest-rerunfailures", "version": "15.1-1", "desc": "A plugin for py.test that re-runs failed tests to eliminate intermittent failures", "csize": "24612", "isize": "115002", "md5sum": "613f5f95075596daf2f008191e4730ec", "sha256sum": "016e91cc70414c029338860c31e46197c6c1d936149dcba10466e3166dbdbe51", "pgpsig": "iQIzBAABCAAdFiEEaLNTfzmjE7PldNBndxk/FSvb5qYFAmgcusMACgkQdxk/FSvb5qbH0w//c6Srp2InJ1GhI7EnsT25uWLrh9t94AnwY/zcs2XRdTbME1UVZ4KjaQvyaJkeW/nmi/2k8k9J3EzPqXFzmw08Ynxf8XFWAUULVE0KeG0mMvim1vy2tsWHCsjvzDfTBGRUrMcvmh+c6JFjACkQV8BIvc4wzAUhKXm7g0wciwYMVKJN6v4GX/irhanWgXuMN+oGzT7MOSPUMnzCvziUft/3HE6MzyesKPMhrASP0wq3UYDXan7KaIhCRVv9lmvt7WwHgEkTCOKih9XXAmHhWXBecaLjWeCaTuOvb6vJvsFhOhRhYgWAB/9k4yTZPN6c/8ccw7WaecaS03mf1IDHgSKm6S0SsVN4UrqyCp4M+9rN6r/+G4/g+1oWcw6VOdyzmWWOrWUxNIyztkSK0Lvs+xCqQI8Jxm0GgWbNTtwm9ENFIoB9ElmmsyS9M4G4/tMSXxpGKkbFYXV+vegOgkVZaoEkfUz+3At6uGlmsukrr1raQRaOrrHVvjGoOughLdkqs8KmjJah2PJyX8+jWUvDH/zI3IY07OuLnFDL2OLXnbMUnRVS3S59bO8B9neKVzLz7aktsQXMnHqHy2k88vf9JBS2LFus7D9rSsSxD1iqtOylnH+/F3OanxXnI7HpxWjwHsr0t1fD+ScwU2loqhSn+bA9Pjs+BfAnJ6Bytifbt5aVJuE=", "url": "https://github.com/pytest-dev/pytest-rerunfailures/", "license": "MPL-2.0", "arch": "any", "builddate": "1746713274", "packager": "Arch Linux ARM Build System <builder+seattle@archlinuxarm.org>"}