{"filename": "haskell-enclosed-exceptions-1.0.3-240-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-240", "desc": "Catching all exceptions from within an enclosed computation", "csize": "17734", "isize": "62396", "md5sum": "5921140dd917936e8f2d2635b011cc7f", "sha256sum": "07310e079405acfc4add348eaf5fccdc6f159f4446d03fe5ca0065df6ffb4e30", "pgpsig": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmVSgycACgkQeGxj8zDXy5KgshAAlhPn0KmUhbyktRPeQverLipqJ8gt04SVXBvHGKR8E+vUb9Hs7pMPd+sKXXs2jWR3ubJG2V4nUvpOmFUFagk99tUbdF8gdhTJVW3+4qVx+nPG5ZTOJTLmq+6qyRj7T5YtbgRiYP0jr9jKnc+4Dk4awOfIe4Y0ckysf18G0E4alkf1GEsVZPaMOPO8/Xp1Ku4KDBZlOJ15hOUkZ3lS3+5LEoGtlqTdcSvFAIxgklClmR7Rdn8wXSooJHyTMnEv8668vVjA/Vm01P6IoJ4V2UjBQlDnRCpK+WK3fDE8t6eNz4T4JJFPcGW5NXMoIn8FKfcNcwv1ve3D50Qi7osrQPgon4iumST6bvhFVRJ2gXJtaVA9Yg8e3+QOGkJkrQ+9q0JqbIEff53QN4kUle2230rmijtVhQUbnhS9oK8US2sOSuBBjDo3y9XL42Ie8pFVYihk+PXFYyhXSakxTMK5GVN7RVBDYaWL+wSaLBzUJszlO3H/qbXRGEkOm0+IGV0w4/Qc+HzjMEEaYtxNx3U2jX6IryIYW6sX1WyEtNWJagAXD3NMXGhka+ydkvPpzkg4UovbCtfyvxT0tpFbEAeY3CF3hWWgUc5QDmNTTrrXqxpdVKwb2aed5yo0oZkYdClIYY6FU20ACqUgoeQek+GAK9N55Ean2/poZGgpERC3IPzh48g=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1699906324", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"], "tokens": ["haskell-enclosed-exceptions", "haskell-enclosed-exceptions_x86_64", "haskell-enclosed-exceptions_unstable", "haskell-enclosed-exceptions_x86_64_unstable"]}