{"filename": "haskell-enclosed-exceptions-1.0.3-235-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-235", "desc": "Catching all exceptions from within an enclosed computation", "csize": "17700", "isize": "62406", "md5sum": "06621ab89cd52603175c1b2274275166", "sha256sum": "619df10b42b174fd032d88db840f7a1bbc89876d0e8a023523ed3e39e3b5e297", "pgpsig": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmUFoxEACgkQeGxj8zDXy5IDYhAAnUKMIuFK47h0ZCRLssnHgEUx4J/4y9mqsbcbnnVggwV4uNicmJMFRizEtcTz/dbTpGG62xz/Yw/ZCp8TMYGf2lPHXPavKmlJ2pXQUp6HaGKjcYM3iqsWEZknwhXee3mUfOrxXbMInGTGoPBUpMnA08k8m6Sy5N1+acOZDm/jOEHM/ijFBi4qKyyF19Id3aI/lfjsjEkfkeXL3pOubgffzByw3Hox3ncDSMlMz0hxSDnLbRk6McgDiPOLDIvMFHKo3Ye8LJcaCiOaIwkF2/CDFmUxEnDhYKyXFyjX/nzhTRHDa0dzmoas/WQ0AOzevOn9tApq9R9EN26mJNb37CQ7MvrbMKti0hX+K/riw80p/ykMOWji43d+r5RFE6EGlKMnUr7UV5TWUAaFt8CIikAjtz9E03l0aoDbrlEml/IZ8zfqoQ8KMZyuw7nh0MCfTOJyPMTGbhcZPXZ/jHBPsHVd/7H5bzQDOx7i7g48tODFNfgxXVMwShtxufdPoqnVn34jzluwL3F0pD4eaeICBLKQutzAP91jF3YNDtuOfWZHUPaizq7hBHfp9B06gvfBHTkHSBY3aMY48JX5GgQQzFmmJVzHS4/66EIbA8cZHvKhbevi0LZW7BhL6O3s92XAny1dJG9VjwOMq1NPYpFtPgt6giblVkmnXGqZBqsYKnfucwc=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1694868218", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"], "tokens": ["haskell-enclosed-exceptions", "haskell-enclosed-exceptions_x86_64", "haskell-enclosed-exceptions_unstable", "haskell-enclosed-exceptions_x86_64_unstable"]}