{"filename": "haskell-enclosed-exceptions-1.0.3-238-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-238", "desc": "Catching all exceptions from within an enclosed computation", "csize": "17700", "isize": "62394", "md5sum": "0d648a1ce52401b530135a5f6bb396b8", "sha256sum": "7b0596deff07ace48a82fdb52dd8c09f7bed6d5e870f5b5b1841417887662657", "pgpsig": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmUduOQACgkQeGxj8zDXy5Io9A/+MCvgFCz+134sQsfMVUKRrGt0chnieZcLal5Z9YvIqcvNBAZ7ctclzzyZRb9zf6Bk6dpcKttG2FWcIrWmsP4pTjDLWiT8V/LVghptmuxWIk8iK0cjQAd9BnMsr8U2yGTswJ/jK22e3QX3Ym1YXoIRgfYN2zvXj8vLDq2MRq/X5VakYWPRu8uX0Laq+0k37vs0RIS+kXtza1oOE4sVK2ry4D6EyO60vdPFDjqgkCHj8pT2M3EooOmP/vW+oxXIacTRkL3J/9ijH28TC6CSK52HFKIwyKYxCfj+I6wzd5UxmhwYPOfnFT9HuMoDQCo+pKt6sYLiUOHcRVr3CGUh4a0ewNorCvby0RcEcIHEJDBfVLDXYFQtnpiAcaHfjsPmKAY5mo+82tGuy+RuaxmToTtCYvbUjC0jV5YHiby9OvR0duUJwhcl9iqwvaktX50oKApFOE6DIxcJr6RuKZs/f/qQ8PvAjVitiTbD/mwaOpzQpUoYZqLn7zCyXpOrjohS4RCOtBM0B2hhwhm/dnoAcSzuT3Qt2cs53Q5ldeg5SMId7OxcnsRxYiRzEuxISdbEY9Yvp25HpKpGMP+Ol73/TmDZGN0QoaFVkxlgmZL660/baV3h8q4rXj8gCfwC/c/H3KvF0uLY4i99lNxX6GnEtG3KYlLw6TMTAwO8icsescjilaQ=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1696446673", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"], "tokens": ["haskell-enclosed-exceptions", "haskell-enclosed-exceptions_x86_64", "haskell-enclosed-exceptions_unstable", "haskell-enclosed-exceptions_x86_64_unstable"]}