{"filename": "lld-17.0.6-1-x86_64.pkg.tar.zst", "name": "lld", "base": "lld", "version": "17.0.6-1", "desc": "Linker from the LLVM project", "csize": "1722807", "isize": "5855823", "md5sum": "fbc183f9893e335916ca97bfc67a89c2", "sha256sum": "2982ff9fe56f973ab3fd7b5bbe31e27451058a478a4808d89a3213d6dddfb8aa", "pgpsig": "iQEzBAABCAAdFiEEhs/8qRjPOvRxR1iAUeixSKmZnDQFAmXjPrMACgkQUeixSKmZnDRBdAgAtOczM2LFbvVxK2mTlmZbI5wtOud7n8NXN1mFCpTisSgCBYM2e1uEMwe5KI3IPIXXnJqGvdrq6galvNyqxUlRsBlRFxCPe6NKh9uylAjDTIE6s7aYyDC+zXyI46n6P23dD/xw9iMyubU2qBU//iZsCmo7ux315rSndEIMBFTsmfsiCZB0V7oO5ejgMLwhy+papXTE0dm3hLbg/Aiut3RIM8UHUjbeY0VLhf3VvqxHK+DvEmtEhvoMJGcSKXp9l6Jk7s4GmliUe+5zs6CIswfOmFmbB+T/EWbvtCy1VpYMMIX94Lj+K/eH2vX6MTFfVdr6GpYR6zMRxR5JF+3TZNS9IA==", "url": "https://lld.llvm.org/", "license": "custom:Apache 2.0 with LLVM Exception", "arch": "x86_64", "builddate": "1709391434", "packager": "Evangelos Foutras <foutrelis@archlinux.org>", "depends": ["llvm-libs", "gcc-libs", "zlib", "zstd"], "makedepends": ["llvm", "cmake", "ninja", "python-sphinx"], "tokens": ["lld", "lld_x86_64", "lld_unstable", "lld_x86_64_unstable"]}