{"filename": "python-better-exceptions-0.3.3-2-any.pkg.tar.zst", "name": "python-better-exceptions", "base": "python-better-exceptions", "version": "0.3.3-2", "desc": "Pretty and useful exceptions in Python, automatically", "csize": "27507", "isize": "91251", "md5sum": "bff554dce72257ba720c866de1055eec", "sha256sum": "e02b73a60af423ecaaf1c1bc830a1a18fad35950269f4e524189956dcddc898c", "pgpsig": "iQIzBAABCAAdFiEEFORv5f1p8uKH4kTbYyw8wNHJyvYFAmdgJJsACgkQYyw8wNHJyvZ4eQ/+OxNjpTdYVypv+Euu6/er1XXPPkowp9soWnA3O87HmtwzU3kk8EzmIsnmp1o5c12dr6k6AKik8qwEmDsg1gH4/tAEHkBu7dDQHyBsPcufWb5WyLH6TFXeSTiokjddDa/CinTrsCb5jpGz0huWXToteE+9J9pXEDDhe5EZ0t2kH9l+1AV81Fea4ueeD7ziOpaesfhkuiQhPiJgFySkb4uSBMjYPg/8fqCnq7FrEbwmk8MucQpgfyPYX487UuX0D3HtauPTWbQUpLMZYiXYPHQze+uCHMIpqHga/guyHD2NgrS9b/rb4r0s0N93cZC7QtLRK5kN6pEBcASmnNz71xHQqmJY2DHKIy6KfZk0BYeVombXXzJcuwI9PRiCTC8FZLn/EfFPEigcbeOspv0UUNbJF6MVhaQtlfvopvL5RBLjeBCMdbqz7049qpIYgLbWTBgcsFHFkLp9vbBv8mfvVLgPj7W5La+rfx54qZekrnMjYRN51zeCdNMwYHtEzqxKkuRBfCTLobpaLUAR/E1B+he4hkjOjpZNeYAdHcIedmDjhkHDAPWfqT8zJ7JAUdQCJMfi9s4RjjqsgkV5+mmN/3ZUrvsbxPXY4AmPX92RHlTLUBzrh//2nxk1UNdmpWbYqFWrAUzD/C5BFsbr0ffOq/925NKT3SYRX6z0Qk1dz/MubF4=", "url": "https://github.com/Qix-/better-exceptions", "license": "MIT", "arch": "any", "builddate": "1734354055", "packager": "Ball\u00f3 Gy\u00f6rgy <bgyorgy@archlinux.org>", "depends": ["python"], "makedepends": ["git", "python-build", "python-installer", "python-setuptools", "python-wheel"]}