{"filename": "python-pytest-rerunfailures-13.0-1-any.pkg.tar.zst", "name": "python-pytest-rerunfailures", "base": "python-pytest-rerunfailures", "version": "13.0-1", "desc": "A plugin for py.test that re-runs failed tests to eliminate intermittent failures", "csize": "25380", "isize": "111581", "md5sum": "419da8e48f4e4f893f50d1080ec8cb92", "sha256sum": "38404cb6032050ae84f71a32af4642ff742b60e34e6a69c9770d3763b6ed86b1", "pgpsig": "iHUEABYKAB0WIQRizHP4hOUpV7L92IObeih9mi7GCAUCZV8zKQAKCRCbeih9mi7GCCroAQDp0FLoTMvXLzv8JSBgPhpFxFRCUCiplu/GTapMtg0BKAD+LwvKp+UrxPNL8XDBIPw9ULEffiGIMR5SlXe/JZhHVQ8=", "url": "https://github.com/pytest-dev/pytest-rerunfailures/", "license": "MPL-2.0", "arch": "any", "builddate": "1700737557", "packager": "David Runge <dvzrv@archlinux.org>", "depends": ["python", "python-importlib-metadata", "python-packaging", "python-pytest"], "optdepends": "python-pytest-xdist: for recovering from crashes", "makedepends": ["python-build", "python-installer", "python-setuptools", "python-wheel"], "checkdepends": ["python-pytest-xdist"], "tokens": ["python-pytest-rerunfailures", "python-pytest-rerunfailures_x86_64", "python-pytest-rerunfailures_unstable", "python-pytest-rerunfailures_x86_64_unstable"]}