{"filename": "haskell-enclosed-exceptions-1.0.3-244-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-244", "desc": "Catching all exceptions from within an enclosed computation", "csize": "17731", "isize": "62400", "md5sum": "75409e357df116445aa6ca114d4b5425", "sha256sum": "9602b08b4d55c504a2c3a57dc5277ff5ccda442af4a2065c54a6c04a2bf06924", "pgpsig": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmVdxJsACgkQeGxj8zDXy5Jk2hAAi/xgYPwyRD1sRRCkFSkwbXNtK0ZYF1ultjwjqzcwo2RyuXiteULpHwtwXvW1J+o3q8ytiitWwZ7rLAobfqqG9nExTz4O8RmuOeVHfZHtbqJiCGetFGcoyWrzNLCPcnGL1xkD8xyZSSV4nJbXYXTTQZTLFnC3EpSwQCPGb3CLuMWg3uE2KcPezkcRariX97hK0jMIxp7cXMBSprzk9z4UxpsfcvGU1GdnqYjuXx7toD8VTMDEFqqbqHXaVAOVi4ScHxHT5hc+g4K6ZHmQ77E4AZ4owxmW0vt4VQMSv6X2TrlIhbT0qAi0maiTiL2TqUlOuE1dO4i6KfYu8yD7mC73vhnc1JO42qZVh+NA3k9/j3SSkIvtKIWeM37Ze4EvkLrQwwV4dw52XcK/JwA2NjjPrx70wpd6F81177rojg8U29eAMMP+I3u5u5ZTaZVRpArwGvKNwEujGW2DeS9NYfQ7x9kUzUQ+JEUS5cWh9DWwIaOFJvYxrfb3fmm92imW8foWrLvyZ2avHK/SmStuNYir41llaKiZi3oCfSQyW8Dwror2HLBTjoI0TErTSyPrp64BJ4dEscFQMu20UeSZU0D1MC9xkVo63D5y5k/LGNkUzFZckuULWkSJpIK1zYUdh/ZDpj7PEiMxjnY+9X2cjHSJycEgIOJQS0oXXS9kFRdyZhg=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1700643975", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"], "tokens": ["haskell-enclosed-exceptions", "haskell-enclosed-exceptions_x86_64", "haskell-enclosed-exceptions_stable", "haskell-enclosed-exceptions_x86_64_stable"]}