{"filename": "python-cfgv-3.3.1-4-any.pkg.tar.zst", "name": "python-cfgv", "base": "python-cfgv", "version": "3.3.1-4", "desc": "Validate configuration and produce human readable error messages", "csize": "17892", "isize": "78740", "md5sum": "6a3d07cd0b994d4a1909e30251f87318", "sha256sum": "a2f173af560d7f4a50354289cc0b04b6df6d316e9930da517eaa0cf6f446b0ec", "pgpsig": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmQuxwkACgkQeGxj8zDXy5K8NhAAk+lDJ3KuDndxrl5oyIQ7euhEXkj6fGsy2/pgWfnMn23rfe/7fLAZBoe5iWv25nnqK1XdlvsWN3DPR1PHPs1c8xuoOY1xPq3gMx3qnxQ7zt5hNH/lZAJMMsVDi2q8qpBozjt9TddCenofwMVXOpv/I0ynTem33QhYaF0Wed193PKAj6GvxlDin+EFKjSkFk6zzTRPBFXcCMeP7PbQ/pErU14RFWjEydhdQ33eiQShaZJcO7PYB4hXNbRA6cGX7aAJDbVAbTpEnh/OVaFOW3/PlJaE3n7m5nGrfX3a6Nr1D605jVAA/wAAwLCyXRAukmJRD1eGObVPRsRcTkmeYR3Y5YaNPaxJRce5P1dwY/kV0aPOMGE7HGTcbq98P4nc60ePpNUcbXRCZufPgnJbAhjhbaGg6odZrbIE3pPOLq2zsVA+w0urBSt6NTfppJ9Ngh2gzMyXrBCjgUhBu4jDaIiOv06D4//lIfuacuACJk8l786BgsVI8SXjuzBSAiSLZu/dOKVTCMpuRx6uJHol1ka2vLlsuCDp6IsdseHe0GUoGA5e2+sNu7NgFiLazFTHNVCglWdYoXArY+vmbaVNnOYkm/Sltb8cmokSrkPlbDuOcN8kiNQnmHNs/kj10C4tXLjy+npWcoeM5FNcRXWbDt8uAhM0kfxB58PbsQkvF+iW1JI=", "url": "https://github.com/asottile/cfgv", "license": "MIT", "arch": "any", "builddate": "1680787166", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["python"], "makedepends": ["python-setuptools"], "checkdepends": ["python-pytest"], "tokens": ["python-cfgv", "python-cfgv_x86_64", "python-cfgv_stable", "python-cfgv_x86_64_stable"]}