{"filename": "python-exceptiongroup-1.3.0-1-any.pkg.tar.zst", "name": "python-exceptiongroup", "base": "python-exceptiongroup", "version": "1.3.0-1", "desc": "Backport of PEP 654 (exception groups)", "csize": "35742", "isize": "147090", "md5sum": "36ec7be69b23e7e378883eea4eb290c1", "sha256sum": "22fb6f7ab48a1f3a6fe99941840ed0e7916d8dc7ef36cfe21ae4c3a2eaf57b77", "pgpsig": "iQIzBAABCAAdFiEEsNZSlUdmBrcfDG+CqF6BHrTKLggFAmggYhYACgkQqF6BHrTKLgjUJg//RJWXm7NwpuC339d/b/3wCQqCt7tuVMuj1RxEZoKhcJxtnRQJrEbkYL8NamzYw11iVa+uyZ3V7A1MCkWnNXRu0M04m15LZtFPSr11OFvR3ZHg1cF34MWaElIAn+uUZ0JgLS0XP22h/TNnTjdg6q1wV0fKISeufzDL2VKtEaZXBQwgMANR5xtJmijgEdRVGIpAi39gijw/pn4/vIRKW3QIkCp7h3ucpGtpUDtLLk0vUtK/sszVs4A4HX3acNgjRlcJrFWx1yR0drItLUmNVXXK6kW5joeHXX8xifdUuecewmmhlTsdbaD6oiwbwsSPB6vWUNnJJa307s3ZiCtQqUPZiKgfOmdMYrWKMmq8HoqjDC6G+DFT01uq+26m60JV/+t/5o/Bs8n5/cmAEZ+nRKWJ4iPtWrJrpcWWVAqvsOaAVUgH5wI9Jy4IQiDrRSkLCYoWsyqHN3+2IB1HKqTK5Ip622xrnH3fCA8yq2xKEz23/+WyEWO5OLj8aMUIzYRWxr66vgeE40trddhhVzCQmgqnXBOBTwF+wRCdRGgxwaht+G6N0thjvNmkp+p7U2g8ez3NXLWMBFpL7BLOI6oHIJQkaClrkkkFp/nCzkakUs7HFNrQLP9HkWShzUhYs/jhVDunT1SP1EtOCHOATK1TTX8vHQwLGLx/4qzLBahzxkdJWxc=", "url": "https://github.com/agronholm/exceptiongroup", "license": "MIT", "arch": "any", "builddate": "1746952710", "packager": "Caleb Maclennan <alerque@archlinux.org>", "depends": ["python"], "makedepends": ["python-build", "python-installer", "python-wheel", "python-flit-scm"], "checkdepends": ["python-pytest"]}